# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Minimal
email: aallysson0@gmail.com
description: "Esse Ã© um blog minimalista criado para aprender jekyll"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://allysson.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: allyssonsantos
github_username:  allyssonsantos
lang: pt-BR

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-admin
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title
disqus: minimal-blog-1
